{{- if and .Values.api.enabled .Values.api.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ragx.fullname" . }}-api
  labels:
    {{- include "ragx.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    {{- toYaml .Values.api.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size | quote }}
  {{- if .Values.api.persistence.storageClass }}
  storageClassName: {{ .Values.api.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
