{{- if not .Values.secrets.externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragx.secretName" . }}
  labels:
    {{- include "ragx.labels" . | nindent 4 }}
type: Opaque
stringData:
  neo4j-password: {{ .Values.secrets.neo4jPassword | quote }}
  minio-access-key: {{ .Values.secrets.minioAccessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  grafana-admin-password: {{ .Values.secrets.grafanaAdminPassword | quote }}
{{- end }}
