{{- if and .Values.worker.enabled .Values.worker.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ragx.fullname" . }}-worker
  labels:
    {{- include "ragx.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  accessModes:
    {{- toYaml .Values.worker.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.worker.persistence.size | quote }}
  {{- if .Values.worker.persistence.storageClass }}
  storageClassName: {{ .Values.worker.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
