"""Core layer (L0): domain models, exception tree, configuration.

Constraints (00-overview.md §0.1, 02-core.md preamble):
    * depends only on stdlib + pydantic
    * no other ragx module may be imported here
"""

from ragx.core.exceptions import (
    AgenticError,
    AllProvidersFailedError,
    AuthError,
    BudgetExceededError,
    ChunkError,
    CircuitOpenError,
    ConfigError,
    DuplicateDocumentError,
    EditConflictError,
    ExtractionSchemaError,
    FilterValidationError,
    GraphError,
    InfraError,
    IngestError,
    LLMError,
    ParseError,
    PluginContractError,
    PluginTimeoutError,
    RAGXError,
    RateLimitError,
    RetrievalError,
    UnsupportedFormatError,
)
from ragx.core.ids import new_id, ulid
from ragx.core.models import (
    Atom,
    AtomDescription,
    AtomType,
    Citation,
    EmbeddedChunk,
    Entity,
    FilterExpr,
    IngestTask,
    QueryResult,
    RawDocument,
    Relation,
    RequestOverride,
    ScoredChunk,
    SubGraph,
    TaskStatus,
    TokenUsage,
    TopicSummary,
)
from ragx.core.roles import LLMRole
from ragx.core.settings import (
    KB,
    BudgetConfig,
    CacheConfig,
    ChunkingOptions,
    CircuitConfig,
    EvalConfig,
    FeatureFlags,
    KBConfig,
    KGExtractionConfig,
    LLMRouterConfig,
    OTelConfig,
    ParseOptions,
    PluginConfig,
    ProviderTarget,
    QueueConfig,
    RoleConfig,
    SecurityConfig,
    Settings,
    effective_kb_config,
)

__all__ = [
    "AllProvidersFailedError",
    "AgenticError",
    "AuthError",
    "Atom",
    "AtomDescription",
    "AtomType",
    "BudgetConfig",
    "BudgetExceededError",
    "CacheConfig",
    "CircuitConfig",
    "CircuitOpenError",
    "ChunkError",
    "ChunkingOptions",
    "Citation",
    "ConfigError",
    "EmbeddedChunk",
    "EditConflictError",
    "Entity",
    "DuplicateDocumentError",
    "EvalConfig",
    "ExtractionSchemaError",
    "FeatureFlags",
    "FilterExpr",
    "FilterValidationError",
    "GraphError",
    "IngestError",
    "IngestTask",
    "KB",
    "KBConfig",
    "KGExtractionConfig",
    "LLMRole",
    "LLMRouterConfig",
    "LLMError",
    "OTelConfig",
    "ParseError",
    "ParseOptions",
    "PluginConfig",
    "PluginContractError",
    "PluginTimeoutError",
    "ProviderTarget",
    "QueryResult",
    "RAGXError",
    "RateLimitError",
    "RawDocument",
    "QueueConfig",
    "Relation",
    "RequestOverride",
    "RetrievalError",
    "RoleConfig",
    "ScoredChunk",
    "SecurityConfig",
    "Settings",
    "SubGraph",
    "TaskStatus",
    "TokenUsage",
    "TopicSummary",
    "UnsupportedFormatError",
    "effective_kb_config",
    "new_id",
    "ulid",
]
